### ISSUE TITLE
如何啟用「冒號－開引號」的標點擠壓

### ISSUE THREAD

**Issue by balthild** [ethantw/Han#104]
[這個知乎回答](https://www.zhihu.com/question/24978750)中提到可以加入相應 CSS 規則來啟用之，但是文檔中未說明需要加入什麼規則。

**Comment by ethantw** [comment]
你好。

目前的版本（v3.3.0）可以用下方的樣式規則來去除「冒號－開引號」間的空隙，但若在複雜的DOM結構下可能無法作用（比如開引號被 `span` 等元素所包圍時）。

```css
h-char[unicode=ff1a] + h-char.bd-open:before {
  display: none;
}
```
