### ISSUE TITLE
标点挤压与 `white-space: nowrap` 冲突

### ISSUE THREAD

**Issue by Hsiao-Feng** [ethantw/Han#120]
当给元素加上
```css
white-space: nowrap;
```
CSS 属性时，如果遇到有标点挤压，会导致标点后的元素换行（图一）。而删除掉右方括号`】`的挤压后，就会达到预期效果（图二）。

图一：

![图一，被挤压换行](https://raw.githubusercontent.com/Hsiao-Feng/Hsiao-Feng/main/images/Snipaste_2022-10-17_20-31-13.jpg)

图二：

![图二，恢复](https://raw.githubusercontent.com/Hsiao-Feng/Hsiao-Feng/main/images/Snipaste_2022-10-17_20-31-30.jpg)

**Comment by Hsiao-Feng** [comment]
到 `han.css` 里看了一下并试了试，似乎是由于这部分造成的：
```css
bd-end:after, h-char.bd-jiya.bd-open:before, h-cs, h-cs[hidden] {
    display: none;
    visibility: hidden;
    content: " ";
    font: .825em Courier;
    letter-spacing: 0;
    white-space: normal
}
```
和其中的 `content` 有关。如果将 `content` 设为空，就不会再换行。
