### ISSUE TITLE
“漢拉間隙”纯CSS解决方案如何处理比较好？

### ISSUE THREAD

**Issue by yisibl** [ethantw/Han#40]
例如：http://jsbin.com/olaFixUJ/1/edit

``` css
:lang(en) {
  margin: auto .25em;
}

:first-child {
    margin-left: 0;
}

:last-child {
    margin-right: 0;
}
```

但是不好处理句子结尾的空隙。

> 此外，`1ch`实际渲染效果并不等同于`.25em`
