### ISSUE TITLE
当字体为宋体时，着重号过粗

### ISSUE THREAD

**Issue by Aaaaaashu** [ethantw/Han#84]
![screen shot 2015-10-15 at 3 29 17 pm](https://cloud.githubusercontent.com/assets/3678166/10507279/f6c3bed0-7351-11e5-8a1a-93b1051ec0e1.png)

**Comment by Aaaaaashu** [comment]
起初，我以为是宋体自身的问题，后来采取以下方案：
```css
em {
  position: relative;
}

em:after {
  position: absolute;
  top: 0.65em;
  left: 0;
  width: 100%;
  font-family: sans-serif; // 设为黑体
  overflow: hidden;
  white-space: nowrap;
  content: "・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・";
}
```

结果，着重号依然过粗。

**Comment by ethantw** [comment]
請使用相應的標點字體，如下：

```css
// 無襯線字體
.sans {
  font-family: 'Biaodian Sans', sans-serif;
}

// 襯線字體
.serif {
  font-family: 'Biaodian Serif', serif; 
}

// 不支援`unicode-range`的瀏覽器
.no-textemphasis em:lang(zh) h-char:after,
.no-textemphasis em:lang(ja) h-char:after {
  font-family: Georgia, 'Time New Roman', Arial, serif;
}
```

詳細中文標點字體列表請見：
<https://css.hanzi.co/manual/wenzisheji#biaodian_yangshi_xiuzheng-zhongwen_biaodian_liebiao>
