### ISSUE TITLE
語言屬性値為「zh」時，即使使用「Biaodian Pro Sans」標點，<blockquote> 內的句號依然會居中

### ISSUE THREAD

**Issue by apm1467** [ethantw/Han#88]
https://jsbin.com/waxocareli/1/edit?html,output

把語言屬性改成 zh-Hans 可以解決這個問題，所以不知是故意如此還是 bug。

**Comment by ethantw** [comment]
在漢字標準格式中，`lang="zh"`預設用於繁體，並且不是推薦的寫法。請思考是否真的需要這麼寫。

不同「情境」下，有不同的預設字體[1]。根據CSS選擇器的優先級，下面的樣式並不會讓網頁中所有元素都使用此一字體設定。

```css
body {  font-family: 'Biaodian Pro Sans', sans-serif;  }
```

漢字標準格式有一套嚴謹的字體回退規則，也在預處理器層面（Sass及Stylus）提供了一套調用接口[2]。還請參考。

\[1]: https://hanzi.pro/manual/wenzisheji#butong_qingjing_xia_de_ziti
\[2]: https://hanzi.pro/manual/sass-api#ziti_jixing_extend
