### ISSUE TITLE
自定義 css 的 ruby rt 字體顏色經  javascript 眩染後顏色回到預設值

### ISSUE THREAD

**Issue by terrylinooo** [ethantw/Han#99]
謝謝您開放這麼棒的 library 我用在我開發的公益網站[字典百科](https://zh.dictpedia.org) ，目前我載入函式庫之後只眩染特定的 class name 用來把字詞音節化標上漢語拼音及注音，目前還在本機測試還沒更新，所以我貼圖說明我的狀況

我用類似這樣的 css 來定義各別顏色，希望給讀者們更好閱讀

```css
.ruby-container rtc rt:nth-child(1) { color: #00a0e9 !important; }
.ruby-container rtc rt:nth-child(2) { color: #eb6877 !important; }
.ruby-container rtc rt:nth-child(3) { color: #f19149 !important; }
```

![1](https://cloud.githubusercontent.com/assets/11989371/23903589/fcd92e28-08ff-11e7-9684-88bccf65b0b9.jpg)

經 js 眩染後

![2](https://cloud.githubusercontent.com/assets/11989371/23903610/0e1d40e8-0900-11e7-98c4-63cd9e5241de.jpg)

查原始 javascript 中並無針對顏色的處理.. 我覺得一頭霧水，不知道是否有個意見讓我解決
